import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const css = await readFile(new URL('../styles.css', import.meta.url), 'utf8');
const js = await readFile(new URL('../app.js', import.meta.url), 'utf8');

assert.match(html, /class="toopeace-wrap"/);
for (const id of ['T', 'O1', 'O2', 'P', 'E1', 'A', 'C', 'E2']) {
  assert.match(html, new RegExp(`data-l="${id}"`));
}
assert.doesNotMatch(html, /class="tp-labels"/);
assert.doesNotMatch(html, /SELECT YOUR EXPERIENCE/);
assert.doesNotMatch(html, /I build cool companies|with cool people\./);
assert.match(html, /TRUE WORK, TRUE LIGHT/);
assert.match(html, /투피스 에이전시는 '고객사를 빛낸다'라는 사명 아래/);
assert.match(html, /class="tp-contact"/);
assert.match(html, />CONTACT<\/button>/);
assert.match(css, /backdrop-filter:\s*blur\(14px\)/);
assert.match(html, /Toopeace와 함께한 사람들은 이렇게 바뀌었습니다/);
assert.match(html, /class="tp-results"/);
assert.match(html, /class="tp-case"/);
assert.match(html, /class="tp-case tp-case--reverse"/);
assert.match(html, /assets\/case-01-marketing\.png/);
assert.doesNotMatch(html, /tp-case-media--split/);
assert.doesNotMatch(html, /assets\/case-02-sleep-card\.png/);
assert.match(html, /assets\/case-02-sleep-profile\.png/);
assert.match(html, /assets\/case-03-phone\.png/);
assert.match(html, /\(현\)연매출 n00억 회사 마케팅팀 교육/);
assert.doesNotMatch(html, /\(현\)연매출 n00억 회사 마케팅팀<\/h3>/);
assert.match(html, /팔로워 400명에서 도합 9만명/);
assert.doesNotMatch(html, /class="tp-case-output"/);
assert.match(html, /월 매출 1억 KPI 달성/);
assert.equal((html.match(/class="tp-social-links"/g) || []).length, 3);
assert.equal((html.match(/data-platform="instagram"/g) || []).length, 3);
assert.equal((html.match(/data-platform="youtube"/g) || []).length, 1);
assert.match(html, /aria-label="소셜 채널"/);
assert.match(html, /class="tp-journey"/);
assert.match(html, /OUR BUSINESS JOURNEY/);
assert.match(html, /안녕하세요, 투피스입니다/);
assert.match(html, /assets\/journey-profile\.png/);
assert.match(html, /class="tp-journey-avatar"/);
assert.match(html, /class="tp-journey-timeline"/);
assert.equal((html.match(/class="tp-journey-paragraph(?:\s[^\"]*)?"/g) || []).length, 5);
assert.equal((html.match(/class="tp-journey-photo-slot(?:\s[^\"]*)?"/g) || []).length, 4);
assert.match(html, /사진 삽입 영역 01/);
assert.match(html, /사진 삽입 영역 04/);
assert.match(html, /창업은 특별한 재능이 있거나 거대한 사명을 가진 사람만 할 수 있는 일이라고 생각했습니다/);
assert.match(html, /투피스는 아직 자신의 강점과 방향을 완전히 찾지 못했지만/);
assert.match(css, /grid-template-columns/);
assert.match(css, /gap: clamp\(64px, 8vw, 112px\)/);
assert.match(css, /translateX\(-32px\)/);
assert.match(css, /translateX\(32px\)/);
assert.match(css, /transition-delay:\s*0\.12s/);
assert.match(css, /\.tp-journey-paragraph/);
assert.match(css, /translateY\(32px\)/);
assert.match(css, /\.tp-journey-paragraph\.is-visible/);
assert.match(css, /\.tp-journey-avatar/);
assert.match(css, /\.tp-journey-photo-slot/);
assert.match(css, /journey-timeline::before/);
assert.match(js, /\.tp-case/);
assert.match(js, /is-visible/);
assert.match(js, /\.tp-journey-paragraph/);
assert.match(css, /min-height:\s*100vh/);
assert.match(css, /min-height:\s*clamp\(620px, 84vh, 840px\)/);
assert.match(css, /padding: clamp\(40px, 4vw, 72px\)/);
assert.match(css, /min-height:\s*76vh/);
assert.match(css, /padding: 56px 20px 110px/);
assert.match(css, /@media\s*\(min-width:\s*769px\)/);
assert.match(css, /prefers-reduced-motion/);
assert.match(css, /3\.6s/);
assert.match(js, /IntersectionObserver/);
assert.match(js, /strokeDashoffset/);
console.log('Toopeace static contract: PASS');
